muhasebeprogrami/Models/ErrorViewModel.cs
namespace muhasebeprogrami.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

muhasebeprogrami/Models/Kasaba.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace muhasebeprogrami.Models
{
    public class Kasaba
    {
        [Key]
        public int Kasaba_Id { get; set; }
        public string Kasaba_Ad { get; set; } = string.Empty;
        [ForeignKey("Sehir")]
        public int Sehir_Id { get; set; }
        public virtual Sehir? Sehir { get; set; }
    }
}

muhasebeprogrami/Models/Okul.cs
namespace muhasebeprogrami.Models
{
    public class Okul
    {
    }
}

muhasebeprogrami/Models/Sehir.cs
using System.ComponentModel.DataAnnotations;

namespace muhasebeprogrami.Models
{
    public class Sehir
    {
        [Key]
        public int Sehir_Id { get; set; }
        public string Sehir_Adi { get; set; } = string.Empty;
        public virtual List<Kasaba>? Kasabas { get; set; }
    }
}

muhasebeprogrami/Models/Unvan.cs
using System.ComponentModel.DataAnnotations;

namespace muhasebeprogrami.Models
{
    public class Unvan
    {
        [Key]
        public int Unvan_Id { get; set; }
        public string Unvan_Adi { get; set; }
    }
}

muhasebeprogrami/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using muhasebeprogrami.Models;
using System.Diagnostics;

namespace muhasebeprogrami.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

muhasebeprogrami/Controllers/SehirController.cs
using Microsoft.AspNetCore.Mvc;
using muhasebeprogrami.Data;
using muhasebeprogrami.Models;

namespace muhasebeprogrami.Controllers
{
    public class SehirController : Controller
    {
        private readonly Context _context;

        public SehirController(Context context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var liste=_context.sehirs.ToList();
            return View(liste);
        }
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(Sehir gelen) {
            _context.sehirs.Add(gelen);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet] 
        public IActionResult Edit(int id)
        {
            var bul = _context.sehirs.Find(id);
            return View(bul);
        }
        [HttpPost]
        public IActionResult Edit(Sehir gelen)
        {
            _context.sehirs.Update(gelen);
            _context.SaveChanges();
             return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var bul = _context.sehirs.Find(id);
            return View(bul);
        }
        [HttpPost]
        public IActionResult Delete(Sehir gelen)
        {
            _context.sehirs.Remove(gelen);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

muhasebeprogrami/Controllers/UnvanController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using muhasebeprogrami.Data;
using muhasebeprogrami.Models;


namespace muhasebeprogrami.Controllers
{
    public class UnvanController : Controller
    {
        private readonly Context _context;
        // GET: UnvanController

        public UnvanController(Context context)
        {
            _context=context;
        }
        public ActionResult Index()
        {
            var listem = _context.unvans.ToList();
            return View(listem);
        }

        // GET: UnvanController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UnvanController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UnvanController/Create
        [HttpPost]
       
        public ActionResult Create(Unvan gelen)
        {
            try
            {
                _context.unvans.Add(gelen);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UnvanController/Edit/5
        public ActionResult Edit(int id)
        {
            var bul = _context.unvans.Find(id);
            return View(bul);
        }

        // POST: UnvanController/Edit/5
        [HttpPost]
       
        public ActionResult Edit(Unvan gelen)
        {
            try
            {
                _context.unvans.Update(gelen);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UnvanController/Delete/5
        public ActionResult Delete(int id)
        {
            var bul = _context.unvans.Find(id);
            return View(bul);
        }

        // POST: UnvanController/Delete/5
        [HttpPost]
       
        public ActionResult Delete(Unvan gelen)
        {
            try
            {
                _context.unvans.Remove(gelen);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

muhasebeprogrami/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

muhasebeprogrami/Views/Sehir/Create.cshtml
@model muhasebeprogrami.Models.Sehir
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<form method="post" action="Create">
    <div class="form-group row">
        <label for="text" class="col-4 col-form-label">İlin Adı</label>
        <div class="col-8">
            <input id="text" asp-for="Sehir_Adi" type="text" class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <div class="offset-4 col-8">
            <button name="submit" type="submit" class="btn btn-primary">Ekle</button>
        </div>
    </div>
</form>

muhasebeprogrami/Views/Sehir/Delete.cshtml
@model muhasebeprogrami.Models.Sehir
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<form method="post" action="Delete">
    <div class="form-group row">
        <input type="hidden" asp-for="Sehir_Id" />
        <label for="text" class="col-4 col-form-label">İlin Adı</label>
        <div class="col-8">
            <input id="text" disabled asp-for="Sehir_Adi" type="text" class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <div class="offset-4 col-8">
            <button name="submit" type="submit" class="btn btn-primary">Silme</button>
        </div>
    </div>
</form>

muhasebeprogrami/Views/Sehir/Edit.cshtml
@model muhasebeprogrami.Models.Sehir
@{
    ViewData["Title"] = "Create";
}

<h1>Edit</h1>

<form method="post" action="Edit">
    <div class="form-group row">
        <input type="hidden" asp-for="Sehir_Id"/>
        <label for="text" class="col-4 col-form-label">İlin Adı</label>
        <div class="col-8">
            <input id="text" asp-for="Sehir_Adi" type="text" class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <div class="offset-4 col-8">
            <button name="submit" type="submit" class="btn btn-primary">Düzelt</button>
        </div>
    </div>
</form>

muhasebeprogrami/Views/Sehir/Index.cshtml
@model List<muhasebeprogrami.Models.Sehir>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<a class="btn btn-primary" asp-action="Create" asp-controller="Sehir">Ekle</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">İlin Adı</th>
            <th scope="col">Düzelt</th>
            <th scope="col">Silme</th>
        </tr>
    </thead>
    <tbody>
        @foreach( var item in Model)
        {
        <tr>
            <th scope="row">1</th>
            <td>@item.Sehir_Adi</td>
            <td><a class="btn btn-warning" asp-action="Edit" asp-controller="Sehir" asp-route-id="@item.Sehir_Id">Düzelt</a></td>
            <td><a class="btn btn-danger" href="/Sehir/Delete/@item.Sehir_Id">Silme</a></td>
        </tr>
        }
      
    </tbody>
</table>

muhasebeprogrami/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - muhasebeprogrami</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/muhasebeprogrami.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">muhasebeprogrami</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sehir" asp-action="Index">İller</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Unvan" asp-action="Index">Unvanlar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - muhasebeprogrami - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

muhasebeprogrami/Views/Unvan/Create.cshtml
@model muhasebeprogrami.Models.Unvan
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>




<form method="post" action="Create">
    <div class="form-group row">
        <label for="text" class="col-4 col-form-label">Ünvanı</label>
        <div class="col-8">
            <input id="text" asp-for="Unvan_Adi" type="text" class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <div class="offset-4 col-8">
            <button name="submit" type="submit" class="btn btn-primary">Ekle</button>
        </div>
    </div>
</form>

muhasebeprogrami/Views/Unvan/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

muhasebeprogrami/Views/Unvan/Edit.cshtml
@model muhasebeprogrami.Models.Unvan
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>


<h1>Edit</h1>

<form method="post" action="Edit">
    <div class="form-group row">
        <input type="hidden" asp-for="Unvan_Id" />
        <label for="text" class="col-4 col-form-label">İlin Adı</label>
        <div class="col-8">
            <input id="text" asp-for="Unvan_Adi" type="text" class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <div class="offset-4 col-8">
            <button name="submit" type="submit" class="btn btn-primary">Düzelt</button>
        </div>
    </div>
</form>

muhasebeprogrami/Views/Unvan/Index.cshtml
@model List<muhasebeprogrami.Models.Unvan>
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<a class="btn btn-primary" asp-action="Create" asp-controller="Unvan">Ekle</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Ünvan Adı</th>
            <th scope="col">Düzelt</th>
            <th scope="col">Silme</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">1</th>
                <td>@item.Unvan_Adi</td>
                <td><a class="btn btn-warning" asp-action="Edit" asp-controller="Unvan" asp-route-id="@item.Unvan_Id">Düzelt</a></td>
                <td><a class="btn btn-danger" href="/Unvan/Delete/@item.Unvan_Id">Silme</a></td>
            </tr>
        }

    </tbody>
</table>